# Generated by Django 4.1.6 on 2023-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_created=True)),
                ("title", models.CharField(max_length=255)),
                ("info", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("updated_at", models.DateField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
    ]
