# Generated by Django 4.1.2 on 2023-02-05 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0002_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ManyToManyField(
                related_name="author", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="doer",
            field=models.ManyToManyField(
                related_name="doer", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
